# The URL the site will be built for
base_url = "https://baptiste.darthenay.fr"

# Used in RSS by default
title = "Baptiste"
description = "batist daʁtənɛ"
language_code = "eo"

# Theme name to use
theme = "hyde"

# Highlight all code blocks found
highlight_code = true

# Which theme to use for the code highlighting. 
# See below for list of accepted values
highlight_theme = "base16-ocean-dark"

# Whether to generate a RSS feed automatically
generate_rss = true

# The number of articles to include in the RSS feed
rss_limit = 20

# Whether to generate a tags page and individual 
# tag pages for pages with tags
generate_tags_pages = true

# Whether to generate a categories page and individual 
# category pages for pages with a category
generate_categories_pages = true

# Whether to compile the Sass files found in the `sass` directory
compile_sass = true


[extra]
# Put all your custom variables here